

[build]
  publish = "client/dist"
  command = "npm run build:client"

# Configuração de redirects para SPA
[[redirects]]
  from = "/gomatoken"
  to = "/gomatoken.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração para formulários
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# Headers específicos para Open Graph
[[headers]]
  for = "/gomatoken"
  [headers.values]
    X-Robots-Tag = "index, follow"
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers para imagens Open Graph
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# Headers para segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Configuração para uploads
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,POST,PUT,DELETE,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

